### PR TITLE
update to jdk 15

### PR DESCRIPTION
**Pull request by LarsEckart**
hello Jon,

it's me again :)
java 15 was released and by not bellsoft also published their docker images, so I wanted to help you with the updates.

I'm a bit confused why this time only 3 files changed, last time it were 4 (the auto-generated Dockerfile this time has no change). Is there a problem with the build script?

As far as i remember, you afterwards also want to rename the repository. Once these changes are done, I'm happy to look into updating the other images to start use jdk15 and also latest junit 5.7 etc

Lars

### CODE REVIEW

**Comment by JonJagger** [comment]
Hi Lars,
I'm away for a short fishing trip. Will look at this when I get back home
next week.
big thanks.
Jon

**Comment by JonJagger** [comment]
Hi Lars :-)
back home again. Super fishing trip :-)

On Tue, Sep 22, 2020 at 11:18 AM Lars Eckart <notifications@github.com>
wrote:

> hello Jon,
>
> it's me again :)
> java 15 was released and by not bellsoft also published their docker
> images, so I wanted to help you with the updates.
>

Super. Big thank you.

> I'm a bit confused why this time only 3 files changed, last time it were 4
> (the auto-generated Dockerfile this time has no change). Is there a problem
> with the build script?
>
Yes and no.
The actual start-point files (as used by the runner in the red/amber/green
test) are created from the git repo.
So suppose you change Dockerfile.base and then run the script...
The script will notice that there is a local change.
It will therefore not git-pull from the local repo (since it would miss the
local change which has not been git committed yet).
Instead it copies the local git repo to /tmp and then does a git commit on
that.
Then it creates the start-point from this /tmp git repo.
In this /tmp git repo the auto-generated Dockerfile is updated.
Then the /tmp git repo is deleted.
The script should copy the /tmp auto-generated Dockerfile back to the
proper repo but it does not. On todo list.
If, after the above, you git commit, then run again, you will see a change
to the auto-generated Dockerfile.


> As far as i remember, you afterwards also want to rename the repository.
>
Yes. All language and start-point Docker images are now properly tagged
(from the 1st 7 chars of the commit sha).
So git repo names (and image names) should drop any versions.
At the moment there are two base languages repos for java:  java  ,  java-14
I've just merged your pull request for the latter.
As I recall, there are some java test-framework images that use the base
images generated from both repos.
I propose:
o) Changing image_name.json in java-14 repo to use { "image_name":
"cyberdojofoundation/java" }
o) Leaving the repo names as they are for now.
o) Upgrading all the java images so they use the new java-14 repo base
image instead.
o) Then deleting the java repo
o) Then renaming the java-14 repo to java

That's a fair amount of work since there are quite a few java test
frameworks.

Once these changes are done, I'm happy to look into updating the other
> images to start use jdk15 and also latest junit 5.7 etc
>
Super. And I'm more than happy to help via zoom etc. I'm free all this
week.

Cheers and thanks again
Jon

**Comment by LarsEckart** [comment]
Both my kids are ill so this week might be difficult :D I'll have a look when time permits and otherwise, having a zoom call when I've a kid free day sounds good. :)

**Comment by JonJagger** [comment]
No rush in the slightest.
Thanks
Jon

**Pull request merged**
